module.exports = {
  User: require("./user.model"),
  Course: require("./course.model"),
  Cart: require("./cart.model"),
  Video: require("./video.model"),
  Audio: require("./audio.model"),
  Pdf: require("./pdf.model"),
  JobPosting: require("./job.model"),
  JobApplication: require("./jobapplication.model"),
  Portfolio: require("./portfolio"),
  PortfolioProject: require("./portfolioProject"),
  PortfolioPhoto: require("./portfolioPhoto"),
  PortfolioAchievement: require("./portfolioAchivements"),
  PortfolioContact: require("./portfolioContact"),
  Payment: require("./payment.model"),
  Order: require("./order.model"),
  Transaction: require("./transaction.model"),
  Comment: require("./comment.model"),
  Newsletter: require("./newslatter"),
  NewsAndBlogs: require("./newsandblogs"),
  Movie: require("./movies"),
  Contact: require("./contactus"),
};